version: '3.7'

services:

  my-app:
    build: .
    image: dockerf1:latest
    ports:
      - 3000:3000

    networks:
      - mongo

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

    networks:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://admin:secret@mongodb:27017/
      - ME_CONFIG_BASICAUTH=false

    networks:
      - mongo

volumes:
  mongo-data:
    driver: local

networks:
  mongo:
    name: mongo-network
    driver: bridge
